core/urls.py
from django.conf.urls import patterns, include, url
from core import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
)

todo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'todo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^core/', include('core.urls',namespace='core')),

)

core/models.py
from django.db import models
 
class Todo(models.Model):

    name = models.CharField(max_length=100, unique=True) 
    description = models.TextField(max_length=200)
    created = models.DateTimeField() 
 
    def __str__(self): 
        return self.name

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from models import Todo
from django.shortcuts import render_to_response
from django.views.generic import CreateView




class CreateView(CreateView):
	template_name ='core/create.html'
	model = Todo
	success_url = '/core/'



def index(request):
	items = Todo.objects.all()

	return render_to_response('core/index.html', {'items': items}) 
	

core/templates/core/create.html
{% extends "core/menu.html" %}

{% block title %}Add a task {% endblock %}
{% block content %}

<h1>Add your new task </h1>
<form method="post" class="form">
{% csrf_token %}
{% for field in form %}
<div class="form-group">
{{ field.errors }}
{{ field.label_tag }}
{{ field }}
</div>
{% endfor %}

<input type="submit" value="Submit" />
</form>
{% endblock %} 

core/templates/core/index.html
{% extends "core/menu.html" %}

{% block content %}

<h2>Todo List </h2>
<table class="table">
<tr>
<th>Name</th>
<th>Created At</th>
<th>Description</th>
</tr>

 
{% for x in items %}
<tr>
<td>{{ x.name }}</td>
<td>{{ x.created|date:"D d M Y" }}</td>
<td>{{ x.description }}</td>
</tr>
{% endfor %}
</table>

{% endblock %} 

core/templates/core/index2.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>   
    <title>Todo </title>
   
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">    
  </head>
  <body>
    <div class="container">
    
    <h1>Django Todo Application </h1>

 
        {% for x in items %}
        <p>Name: {{ x.name }} </p>
        <p>Creadet at: {{ x.created|date:"D d M Y" }}</p>
 
        <p>Description:{{ x.description }}</p>

        {% endfor %}    
    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

core/templates/core/menu.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

<title>Todo Application</title>

<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/simple-sidebar.css" %}">

</head>
<body>
<div id="wrapper">

<div id="sidebar-wrapper">
<ul class="sidebar-nav">
<li class="sidebar-brand">
<a href="{% url 'core:index' %}">
Django Todo App
</a>
</li>
<li>
<a href="{% url 'core:create' %}">Add Task</a>
</li>
<li>
<a href="#">Continuing</a>
</li>
<li>
<a href="#">Complited</a>
</li>
<li>
<a href="#">Rejected</a>
</li>
<li>
<a href="#">About</a>
</li>
<li>
<a href="#">Contact</a>
</li>
</ul>
</div>

<div id="page-content-wrapper">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">

{% block content %}

{% endblock %} 

</div>
</div>
</div>
</div>
<!-- /#page-content-wrapper -->
</div>
<!-- /#wrapper -->
<!-- jQuery -->
<script src="js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>
<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
e.preventDefault();
$("#wrapper").toggleClass("toggled");
});
</script>
</body>
</html>